import {
  LazyMotion,
  m,
  domAnimation,
  useAnimation,
  motion,
} from 'framer-motion';
import type { NextPage } from 'next';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import Link from 'next/link';
import { useInView } from 'react-intersection-observer';

import {
  containerClasses,
  linkClasses,
  sectionBodyClasses,
  switchableTexts,
} from '../components/styles';

const BackgroundComponent = dynamic(() =>
  import('../components/background/Background').then(
    ({ Background }) => Background
  )
);
const Card = dynamic(() => import('../components/cards/Card'), {
  ssr: false,
});
const InternshipsList = dynamic(
  () => import('../components/index/InternshipsList'),
  {
    ssr: false,
  }
);
const Activities = dynamic(() => import('../components/index/Activities'), {
  ssr: false,
});
const LinkToSection = dynamic(
  () => import('../components/index/LinkToSection'),
  {
    ssr: false,
  }
);
const CardGrid = dynamic(() => import('../components/cards/CardGrid'), {
  ssr: false,
});
const Header = dynamic(() => import('../components/global/Header'), {
  ssr: false,
});
const NameTitle = dynamic(() => import('../components/index/NameTitle'), {
  ssr: false,
});
const ProjectsList = dynamic(() => import('../components/index/ProjectsList'), {
  ssr: false,
});
const SectionTitle = dynamic(() => import('../components/index/SectionTitle'), {
  ssr: false,
});

const Home: NextPage = () => {
  const { inView, ref } = useInView();
  const animationControl = useAnimation();
  const { t } = useTranslation('common');

  if (inView) {
    animationControl.start({
      x: 0,
      transition: {
        delay: 0.5,
      },
    });
  }
  return (
    <div>
      <Head>
        <title className="text-center">Brahim Abdelli</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <BackgroundComponent />
        <Header />
        <LazyMotion features={domAnimation}>
          <section className="z-50">
            <div className="min-h-screen flex flex-col justify-center relative">
              <div className={`${containerClasses}`}>
                <m.div
                  initial={{ opacity: 0, scale: 1, y: -100 }}
                  animate={{ opacity: 1, scale: 1, y: 0 }}
                  exit={{ opacity: 0, scale: 1, y: 100 }}
                >
                  <NameTitle big accentText={`${t('home.hello')}`}>
                    Brahim Abdelli
                  </NameTitle>
                </m.div>
                <div className="h-4 sm:h-0 mt-8"></div>
                <div className={sectionBodyClasses}>
                  <LinkToSection
                    title={`${t('home.aboutme.name')}`}
                    href="about"
                  >
                    {`${t('home.aboutme.description1')}`}
                    <br />
                    {`${t('home.aboutme.description2')}`}
                    <br />
                    {`${t('home.aboutme.description3')}`}
                  </LinkToSection>
                  <LinkToSection
                    title={`${t('home.projects.name')}`}
                    href="projects"
                  >
                    {t('home.projects.bio')}
                  </LinkToSection>
                  <LinkToSection
                    title={`${t('home.workexperience.name')}`}
                    href="experience"
                  >
                    {`${t('home.workexperience.bio')}`}
                  </LinkToSection>
                  <LinkToSection
                    title={`${t('home.internships.name')}`}
                    href="internships"
                  >
                    {`${t('home.internships.bio')}`}
                  </LinkToSection>
                  <LinkToSection
                    title={`${t('home.school.name')}`}
                    href="school"
                  >
                    {`${t('home.school.description1')}`}
                  </LinkToSection>
                  <LinkToSection
                    title={`${t('home.activities.name')}`}
                    href="activities"
                  >
                    {`${t('home.activities.bio')}`}
                  </LinkToSection>
                </div>
                <div className="h-6 md:h-8 xl:h-16"></div>
                <div className="flex space-x-3 font-mono text-slate-400 sm:text-lg md:text-xl">
                  <Link
                    href="mailto:brahim.abdelli994@gmail.com"
                    target="_blank"
                  >
                    <a className={linkClasses} target="_blank">
                      Email
                    </a>
                  </Link>
                  ·
                  <Link href="https://github.com/BrahimAbdelli" target="_blank">
                    <a className={linkClasses} target="_blank">
                      Github
                    </a>
                  </Link>
                  ·
                  <Link href="https://www.linkedin.com/in/brahimabdelli/">
                    <a className={linkClasses} target="_blank">
                      Linkedin
                    </a>
                  </Link>
                </div>
              </div>
            </div>
            <div className={containerClasses} id="about" ref={ref}>
              <motion.div
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                transition={{ duration: 0.2, delay: 0.2 }}
                variants={{
                  visible: { opacity: 1, scale: 1 },
                  hidden: { opacity: 0, scale: 0 },
                }}
                whileHover={{ scale: 1.009 }}
              >
                <SectionTitle big accentText="01">
                  {`${t('home.aboutme.name')}`}
                </SectionTitle>
                <div className={`${sectionBodyClasses}`}>
                  <p className={`${switchableTexts}`}>
                    {`${t('home.aboutme.bio1')}`}
                  </p>
                  <p className={`${switchableTexts}`}>
                    {`${t('home.aboutme.bio2')}`}
                  </p>
                  <p className={`${switchableTexts}`}>
                    {`${t('home.aboutme.bio3')}`}
                  </p>
                </div>
              </motion.div>
            </div>

            <div className={containerClasses} id="projects">
              <motion.div
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                transition={{ duration: 0.2, delay: 0.2 }}
                variants={{
                  visible: { opacity: 1, scale: 1 },
                  hidden: { opacity: 0, scale: 0 },
                }}
              >
                <SectionTitle big accentText="02">
                  {`${t('home.projects.name')}`}
                </SectionTitle>
                <div className={sectionBodyClasses}>
                  <p className={`${switchableTexts}`}>
                    {`${t('home.projects.description')}`}
                  </p>
                </div>
                <div className="h-8 lg:h-12"></div>
                <ProjectsList />
              </motion.div>
            </div>

            <div className={containerClasses} id="experience">
              <motion.div
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                transition={{ duration: 0.2, delay: 0.2 }}
                variants={{
                  visible: { opacity: 1, scale: 1 },
                  hidden: { opacity: 0, scale: 0 },
                }}
              >
                <SectionTitle big accentText="03">
                  {`${t('home.workexperience.name')}`}
                </SectionTitle>
                <div className={`${sectionBodyClasses} ${switchableTexts}`}>
                  <p>{`${t('home.workexperience.description')}`}</p>
                  <a
                    href="https://tn.linkedin.com/company/majda-smart-solutions"
                    className="inline-flex items-center justify-center px-6 py-3 border border-transparent text-base font-medium rounded-md text-white bg-slate-800 hover:bg-slate-700 md:py-4 md:text-lg md:px-8 transition"
                  >
                    Majda Smart Solutions
                  </a>
                </div>
              </motion.div>
            </div>

            <div className={containerClasses} id="internships">
              <motion.div
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                transition={{ duration: 0.2, delay: 0.2 }}
                variants={{
                  visible: { opacity: 1, scale: 1 },
                  hidden: { opacity: 0, scale: 0 },
                }}
              >
                <SectionTitle big accentText="04">
                  {`${t('home.internships.name')}`}
                </SectionTitle>
                <div className={sectionBodyClasses}>
                  <p>{`${t('home.internships.description')}`}</p>
                </div>
                <div className="h-8 lg:h-12"></div>
                <InternshipsList />
              </motion.div>
            </div>

            <div className={containerClasses} id="school">
              <motion.div
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                transition={{ duration: 0.2, delay: 0.2 }}
                variants={{
                  visible: { opacity: 1, scale: 1 },
                  hidden: { opacity: 0, scale: 0 },
                }}
              >
                <SectionTitle big accentText="05">
                  {`${t('home.school.name')}`}
                </SectionTitle>
                <div className={sectionBodyClasses}>
                  <p>{`${t('home.school.description2')}`}</p>
                </div>
                <div className="h-8 lg:h-12"></div>
                <CardGrid>
                  <Card title="ESPRIT" link="https://esprit.tn/" highlighted>
                    {`${t('home.school.espritinfo.bio')}`}
                    {`${t('home.school.espritinfo.description')}`}
                  </Card>
                  <Card title="ESPRIT" link="https://esprit.tn/" highlighted>
                    {`${t('home.school.espritelectro.description')}`}
                  </Card>
                  <Card
                    title="ISET Rades"
                    link="http://www.isetr.rnu.tn/"
                    highlighted
                  >
                    {`${t('home.school.isetrades.description')}`}
                  </Card>
                </CardGrid>
              </motion.div>
            </div>

            <div className={containerClasses} id="activities">
              <motion.div
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                transition={{ duration: 0.2, delay: 0.2 }}
                variants={{
                  visible: { opacity: 1, scale: 1 },
                  hidden: { opacity: 0, scale: 0 },
                }}
              >
                <SectionTitle big accentText="06">
                  {`${t('home.activities.name')}`}
                </SectionTitle>
                <div className={sectionBodyClasses}>
                  <p>{`${t('home.activities.description')}`}</p>
                </div>
                <div className="h-8 lg:h-12"></div>
                <Activities />
              </motion.div>
            </div>

            <div className={containerClasses} id="contact">
              <SectionTitle big accentText="07">
                {`${t('home.contanctme')}`}
              </SectionTitle>
              <div className="flex space-x-3 font-mono text-slate-400 sm:text-lg md:text-xl">
                <Link href="mailto:brahim.abdelli994@gmail.com" target="_blank">
                  <a className={linkClasses} target="_blank">
                    Email
                  </a>
                </Link>
                ·
                <Link href="https://github.com/BrahimAbdelli" target="_blank">
                  <a className={linkClasses} target="_blank">
                    Github
                  </a>
                </Link>
                ·
                <Link href="https://www.linkedin.com/in/brahimabdelli/">
                  <a className={linkClasses} target="_blank">
                    Linkedin
                  </a>
                </Link>
              </div>
            </div>

            <div className="h-8 md:h-12 lg:h-16"></div>

            <div className={`${containerClasses} pb-6 md:pb-12 lg:pb-24`}>
              <div className="font-mono dark:text-slate-400 text-slate-600 text-xs md:text-sm lg:text-base">
                {`${t('home.copyright')}`} {new Date().getFullYear()} Brahim
                Abdelli.
                <br />
                {`${t('home.takecare')}`}
              </div>
            </div>
          </section>
        </LazyMotion>
      </main>
    </div>
  );
};
export default Home;

export const getStaticProps = async ({ locale }: { locale: string }) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common'])),
  },
});
